In [1]:
from sklearn import datasets
breast_cancer = datasets.load_breast_cancer()
breast_data = breast_cancer.data
breast_labels = breast_cancer.target

print(breast_data.shape)
print(breast_labels.shape)

import numpy as np
labels = np.reshape(breast_labels,(569,1))
final_breast_data = np.concatenate([breast_data,labels],axis=1)
final_breast_data.shape

import pandas as pd
breast_dataset = pd.DataFrame(final_breast_data)
features = breast_cancer.feature_names
features

final_breast_data[0:5]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(breast_data,
        breast_labels, random_state=52)

print(X_train.shape, X_test.shape)

from sklearn import decomposition
pca = decomposition.PCA(n_components=20, whiten=True)
pca.fit(X_train)

print(pca.components_.shape)

X_train_pca = pca.transform(X_train)
X_test_pca = pca.transform(X_test)
print(X_train_pca.shape)

print(X_test_pca.shape)

from sklearn import svm
clf = svm.SVC(C=5., gamma=0.001)
clf.fit(X_train_pca, y_train)

from sklearn import metrics
y_pred = clf.predict(X_test_pca)
print(metrics.classification_report(y_test, y_pred))

print(metrics.confusion_matrix(y_test, y_pred))

iris = datasets.load_iris()
iris_data = iris.data
iris_labels = iris.target

print(iris_data.shape)
print(iris_labels.shape)

features = iris.feature_names
features

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_data,
        iris_labels, random_state=52)

print(X_train.shape, X_test.shape)

from sklearn import decomposition
pca = decomposition.PCA(n_components=2, whiten=True)
pca.fit(X_train)

print(pca.components_.shape)

X_train_pca = pca.transform(X_train)
X_test_pca = pca.transform(X_test)
print(X_train_pca.shape)

print(X_test_pca.shape)

from sklearn import svm
clf = svm.SVC(C=5., gamma=0.001)
clf.fit(X_train_pca, y_train)

from sklearn import metrics
y_pred = clf.predict(X_test_pca)
print(metrics.classification_report(y_test, y_pred))

print(metrics.confusion_matrix(y_test, y_pred))

(569, 30)
(569,)
(426, 30) (143, 30)
(20, 30)
(426, 20)
(143, 20)
              precision    recall  f1-score   support

           0       1.00      0.92      0.96        50
           1       0.96      1.00      0.98        93

    accuracy                           0.97       143
   macro avg       0.98      0.96      0.97       143
weighted avg       0.97      0.97      0.97       143

[[46  4]
 [ 0 93]]
(150, 4)
(150,)
(112, 4) (38, 4)
(2, 4)
(112, 2)
(38, 2)
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.45      1.00      0.62        13
           2       0.00      0.00      0.00        16

    accuracy                           0.58        38
   macro avg       0.48      0.67      0.54        38
weighted avg       0.39      0.58      0.45        38

[[ 9  0  0]
 [ 0 13  0]
 [ 0 16  0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
